### PR TITLE
Fix: Quick switch to background -> black screen

### PR DESCRIPTION
**Pull request by orkenstein**
There is a chance, that you hit home button too quick, when PlayerLayer still have no Player.

### CODE REVIEW

**Comment by 0xced** [comment]
I cherrky-picked 7d3a8b31824afe7151aceaa3ae98f92b8167889e in the `develop` branch, thanks!

**Comment by orkenstein** [comment]
You are welcome!
Why this super useful extension is not in Sources?

**Comment by 0xced** [comment]
Because it’s a hack and I don’t want to support it as part of the XCDYouTubeKit library.

**Comment by orkenstein** [comment]
Well, after all, it works! 
I'm going to use it in production. Thanks for this great feature!

**Pull request closed without merging**
