### PR TITLE
Add ability to fetch videos allowed to be watched on youtube only

### PR DESCRIPTION
**Pull request by k06a**
Should solve this issue: https://github.com/0xced/XCDYouTubeKit/issues/309

### CODE REVIEW

**Comment by dnfodjo** [comment]
Hi, I am still having that issue even after adding line of code

**Comment by k06a** [comment]
@dnfodjo are you sure you have exactly this issue? Video should be watched on YouTube site only?

**Comment by k06a** [comment]
@dnfodjo I had tested it on this video: https://www.youtube.com/watch?v=GVV06jTYjeY

**Comment by HernanPaez** [comment]
@k06a It doesn't work with this video https://www.youtube.com/watch?v=JGwWNGJdvx8

**Comment by HernanPaez** [comment]
@k06a Nevermind. I was testing on an old version of XCDYouTubeKit (2.5.4) the newest version is 2.5.5

**Comment by k06a** [comment]
Why not to fix this one-line fix?

**Comment by nabeelahmed87** [comment]
Its not working with this url 

https://www.youtube.com/watch?v=pqU29nHc-U0

**Comment by SoneeJohn** [comment]
@k06a Closing due to being an old PR. If you still wish to work on this please reopen a new PR and I'll review it.

**Comment by SoneeJohn** [comment]
@k06a sorry I just needed to review it and rerun the unit test since the PR was old. Thanks for your contribution :-)

**Pull request merged**
