### PR TITLE
Error should always contain the video

### PR DESCRIPTION
**Pull request by peterpaulis**
The returned error should always contain the video object... this can be desired in the case of a fallback behaviour, when the direct video streaming is not available, but the app wants to show the thumb, title etc and probably open a webview

### CODE REVIEW

**Comment by peterpaulis** [comment]
Can you pls marge?

**Comment by SoneeJohn** [comment]
Unfortunately, this doesn't fit with how the library works.

**Comment by peterpaulis** [comment]
What do you mean by that?

**Comment by peterpaulis** [comment]
Yup, but the AVPlayerViewController is recommended in favour of the old deprecated MP classes

**Pull request closed without merging**
