### PR TITLE
Added array of thumbnail URLs and deprecated the single small thumbnail URL

### PR DESCRIPTION
**Pull request by matteogobbi**
The array of thumbnails URLs contains several thumbnails in order of size. It would be great to have it available rather than only grab the smallest.

Thanks.

### CODE REVIEW

**Comment by matteogobbi** [comment]
Hey, sorry yesterday I had to update the pod spec pointing to my repository in order to use the library for my needs. It didn't mean to include that commit in this pull request.

**Comment by SoneeJohn** [comment]
@matteogobbi no problem :-)

**Comment by SoneeJohn** [comment]
Thanks for your contribution! I'll check it in more detail tomorrow :-)

**Comment by matteogobbi** [comment]
A change that you could do to make it even better is to also extract the size from the dictionary of the thumbnail.

**Pull request merged**
