### PR TITLE
Changed for query update needed, June 2021 Google update

### PR DESCRIPTION
**Pull request by ryanfrancesconi**
```
        NSDictionary *query = @{ @"video_id": self.videoIdentifier,
                                 @"hl": self.languageIdentifier,
                                 @"el": eventLabel,
                                 @"ps": @"default",
                                 @"html5" : @"1",
                                 @"eurl": [@"https://youtube.googleapis.com/v/" stringByAppendingString: self.videoIdentifier],
                                 @"c": @"TVHTML5",
                                 @"cver": @"6.20180913"};
```

### CODE REVIEW

**Comment by ryanfrancesconi** [comment]
yet another PR for this problem. not sure why CI fails as the change is minor.

**Comment by cyb3rsalih** [comment]
though, works now?

**Comment by cyb3rsalih** [comment]
Quick fix:
Change the row in pods
`pod 'XCDYouTubeKit', '~> 2.8'`
to
`pod 'XCDYouTubeKit', git: 'https://github.com/ryanfrancesconi/XCDYouTubeKit', branch: 'add', submodules: true`

and `$pod update` to terminal in `app/ios` directory

**Comment by ryanfrancesconi** [comment]
> though, works now?

yes it does work with the change above!

**Comment by ryanfrancesconi** [comment]
> Quick fix:
> Change the row in pods
> `pod 'XCDYouTubeKit', '~> 2.8'`
> to
> `pod 'XCDYouTubeKit', git: 'https://github.com/ryanfrancesconi/XCDYouTubeKit', branch: 'add', submodules: true`
> 
> and `$pod update` to terminal in `app/ios` directory

@cyb3rsalih if you use pods... Pointing at my subbranch isn't really a long term fix.

Ideally the repository owner @0xced  would merge the PR and allow everyone to keep using the framework from the correct git url, but perhaps they are offline for sometime.

**Comment by cyb3rsalih** [comment]
@ryanfrancesconi I know, its just a quick fix 🙃

**Comment by ryanfrancesconi** [comment]
@0xced Appears there is something wrong with the CircleCI setup which is throwing errors. I'm not a user of that and not interested to open my account to that service, so I don't know why - but that's why all the PRs are failing...

**Comment by Nyl000** [comment]
Hi, can you resolve this PR issue and merge it please ? Forking and adapting the pod file with another git repo is not a good solution for maintainability.

**Comment by rbrand21** [comment]
This appears to be broken again. Pointed my podfile at your branch: `pod 'XCDYouTubeKit', git: 'git@github.com:ryanfrancesconi/XCDYouTubeKit.git', branch: 'add'` and getting the same error:

`2021-07-23 17:20:17.964818-0700 Renegade Rehab[7294:2399174] [XCDYouTubeKit] Video operation finished with error: The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -3.)
Domain: XCDYouTubeVideoErrorDomain
Code:   -3`

**Comment by ryanfrancesconi** [comment]
@rbrand21 yes, it does appear they broke it yet again. Seems likely this approach is nearing the end of its usefulness.

**Comment by rbrand21** [comment]
@ryanfrancesconi Any suggestions? Including new plugin suggestions...lol

**Comment by ryanfrancesconi** [comment]
@rbrand21 i need to look into this myself... so we'll see. given it's against the you tube terms of service, i assume this framework has given up.

**Comment by cyb3rsalih** [comment]
It starts to work again :)

**Comment by ryanfrancesconi** [comment]
> It starts to work again :)

it does?

**Comment by cyb3rsalih** [comment]
that time it was working. now starts to crash again. I am trying to shift  iframe mode  which is official

**Comment by devDWI** [comment]
Any idea?

**Comment by shadyshrif** [comment]
I think this issue is coming again

**Comment by haroonakram** [comment]
any solution for this?

**Comment by rbrand21** [comment]
> any solution for this?

I ditched this plugin and went for opening youtube videos in a web browser which defaults to using the youtube app on the phone, if installed.
I had so many problems with this plugin over the last couple years. It was wonderful finally ripping it out.
There's now an app switch to YT but I didn't find it _that_ disruptive.

**Pull request closed without merging**
