### PR TITLE
Library Cleanup

### PR DESCRIPTION
**Pull request by SoneeJohn**

### CODE REVIEW

**Comment by SoneeJohn** [comment]
Need to make some more changes.

**Comment by SoneeJohn** [comment]
Updating existing tests

**Comment by Sokalay** [comment]
> Updating existing tests

Thank you so much, it is working.

**Comment by CWftw** [comment]
Is anyone else experiencing no longer getting back 720p (itag 22) on music videos? For example: https://www.youtube.com/watch?v=yWfsla_Uh80

**Comment by SoneeJohn** [comment]
@CWftw that video does have an 720p version but it does not contain audio (itag 136)

**Comment by eloyer** [comment]
Thanks @SoneeJohn for the fix—are you planning to address the failed checks?

**Comment by fragm** [comment]
@CWftw I encountered the same issue. I can't get 720p on all music videos since yesterday.

**Comment by eloyer** [comment]
Thank you @SoneeJohn — @0xced what are prospects for a merge? (Would love to see this fix added to a release so the CocoaPods distro can be updated.) Thanks!

**Pull request merged**
