### PR TITLE
Fixed user no found issue

### PR DESCRIPTION
**Pull request by kosswong**
As titled, one of the solution

### CODE REVIEW

**Comment by hoabv** [comment]
thanks!

**Comment by edcastparesh** [comment]
it is not working

**Comment by kosswong** [comment]
> it is not working

Did you try another youtube link? Sometimes you may need to remove the 720P standard for your AVPlayerViewController. 

`NSURL *streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityHD720)] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];`

to

`NSURL *streamURL = streamURLs[XCDYouTubeVideoQualityHTTPLiveStreaming] ?: streamURLs[@(XCDYouTubeVideoQualityMedium360)] ?: streamURLs[@(XCDYouTubeVideoQualitySmall240)];`


Or, could you paste the error message here?

**Comment by kosswong** [comment]
Take reference to https://github.com/0xced/XCDYouTubeKit/issues/548

**Pull request closed without merging**
