### PR TITLE
add fallback for signature function regex

### LINKED ISSUE #382: -2 The operation couldn’t be completed. (XCDYouTubeVideoErrorDomain error -2.)
Is this the end of XCDYouTubeVideo?

### PR DESCRIPTION
**Pull request by marktgodfrey**
Fix #382 by adding fallback for regex parsing the javascript signature function

### CODE REVIEW

**Comment by JmyW** [comment]
Same as @darkForestCat, moved all lib. files into my project for resolving it. :-) 
Thanks for everyone who joint this discussion and shared information.

**Comment by Spr-Luis** [comment]
Works!! 👍

**Comment by oososo** [comment]
@SoneeJohn  Hi , SoneeJohn , How to use that change? Could you kindly to tell me.Thank you very very much.

**Comment by jm555jm** [comment]
`NSString* pattern = @"[\"']signature[\"']\\s*,\\s*([^\\(]+)";
    NSRegularExpression *signatureRegularExpression = [NSRegularExpression regularExpressionWithPattern:pattern options:NSRegularExpressionCaseInsensitive error:NULL];
    NSArray<NSTextCheckingResult *> *signatureResults =  [signatureRegularExpression matchesInString:script options:(NSMatchingOptions)0 range:NSMakeRange(0, script.length)];
    
    pattern = @"(\\w+)\\s*=\\s*function\\((\\w+)\\).\\s*\\2=\\s*\\2\\.split\\(\"\"\\)\\s*;";
    signatureRegularExpression = [NSRegularExpression regularExpressionWithPattern: pattern options:NSRegularExpressionCaseInsensitive error:NULL];
    // signatureResults.count. now not zero, so do merge the array instead.
    NSArray<NSTextCheckingResult *> *otherResult =  [signatureRegularExpression matchesInString:script options:(NSMatchingOptions)0 range:NSMakeRange(0, script.length)];
    signatureResults = [signatureResults arrayByAddingObjectsFromArray:otherResult];`

**Comment by SoneeJohn** [comment]
@oososo this isn't working at the moment. Working on a fix now

**Comment by oososo** [comment]
> @oososo this isn't working at the moment. Working on a fix now

Thank you . I will waiting online until you fix that.

**Comment by shiningjason** [comment]
I have changed this commit to the following and it works
https://github.com/positive-grid/XCDYouTubeKit/commit/121bd5411c3eb2931f4902be5113da28e43e5b55

**Comment by jm555jm** [comment]
image

 "signatureResults.count" may not zero, so do merge array instead.

Try this:
`
NSString* pattern = @"[\"']signature[\"']\\s*,\\s*([^\\(]+)";
    NSRegularExpression *signatureRegularExpression = [NSRegularExpression regularExpressionWithPattern:pattern options:NSRegularExpressionCaseInsensitive error:NULL];
    NSArray<NSTextCheckingResult *> *signatureResults =  [signatureRegularExpression matchesInString:script options:(NSMatchingOptions)0 range:NSMakeRange(0, script.length)];    
    pattern = @"(\\w+)\\s*=\\s*function\\((\\w+)\\).\\s*\\2=\\s*\\2\\.split\\(\"\"\\)\\s*;";
    signatureRegularExpression = [NSRegularExpression regularExpressionWithPattern: pattern options:NSRegularExpressionCaseInsensitive error:NULL];
    // signatureResults.count may not zero, so do merge array instead.
    NSArray<NSTextCheckingResult *> *otherResult =  [signatureRegularExpression matchesInString:script options:(NSMatchingOptions)0 range:NSMakeRange(0, script.length)];
    signatureResults = [signatureResults arrayByAddingObjectsFromArray:otherResult];`

**Comment by SoneeJohn** [comment]
```

NSArray<NSString *>*patterns = @[@"/.sig\\|\\|([[a-zA-Z0-9$]+)\\(", @"yt\\.akamaized\\.net/\\)\\s*\\|\\|\\s*.*?\\s*c\\s*&&d.set\\([^,]+\\s*,\\s*(?<sig>[a-zA-Z0-9$]+)", @"\\bcs*&&\\s*d\\.set\\([^,]+\\s*,\\s*([a-zA-Z0-9$]+)\\C"];
    
    NSRegularExpression *signatureRegularExpression = nil;
    NSArray<NSTextCheckingResult *> *signatureResults = nil;

    for (NSString *pattern in patterns) {
        
        NSRegularExpression *regex = [NSRegularExpression regularExpressionWithPattern:pattern options:NSRegularExpressionCaseInsensitive error:NULL];
        NSArray<NSTextCheckingResult *> *regexResults =  [regex matchesInString:script options:(NSMatchingOptions)0 range:NSMakeRange(0, script.length)];
        
        if (regexResults.count != 0)
        {
            signatureRegularExpression = regex;
            signatureResults = regexResults;
            break;
        }
    }

```

**Comment by oososo** [comment]
@shiningjason @SoneeJohn 

Thank you very much. I try your code, it work now.

**Comment by SoneeJohn** [comment]
I think I came up with a solution see #390

**Comment by oososo** [comment]
Yes. It work.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Soneé John <notifications@github.com>
发送时间: Friday, September 14, 2018 1:44:38 PM
收件人: 0xced/XCDYouTubeKit
抄送: oososo; Mention
主题: Re: [0xced/XCDYouTubeKit] add fallback for signature function regex (#383)


I think I came up with a solution see #390<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F0xced%2FXCDYouTubeKit%2Fpull%2F390&data=02%7C01%7C%7Caee1955d80e24d24dd3008d61a05295c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636725006793090354&sdata=7x06BggM8JJk%2Fumd%2FACvnYXgQai0zjdmT3ga01Ng2%2Bw%3D&reserved=0>

―

**Comment by alkait** [comment]
> Works!! 👍

No Actually it doesn't work for all videos.  I am facing "**No signature function in player script**" exceptions.  I believe the regex need to be fixed.

**Comment by SoneeJohn** [comment]
@alkait Can you let me know which version that would be?

**Comment by marktgodfrey** [comment]
seems like @SoneeJohn has it with #390

**Pull request closed without merging**
